[theme]
builtin = "Ayu"

[theme.templates]
builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "helix", "hyprland", "kcolorscheme", "qt", "starship" ]
community_ids = [ "fzf", "prismlauncher" ]

[wallpaper]
directory = "~/.local/share/wallpapers"

[shell]
setup_wizard_enabled = false
external_ip_enabled = true
screen_time_enabled = true
date_format = "%A, %B %d"
corner_radius_scale = 0.3
launch_apps_as_systemd_services = true
avatar_path = "~/.local/share/avatars/bokoblin.png"
polkit_agent = true

[shell.animation]
enabled = false

[shell.panel]
open_near_click_control_center = true
open_near_click_wallpaper = true

[shell.greeter_sync]
auto_sync = true

[osd.kinds]
media = false

[location]
auto_locate = true

[bar.default]
margin_ends = 0
radius = 0
end = [
  "media",
  "spacer_3",
  "tray",
  "bluetooth",
  "volume",
  "brightness",
  "spacer_2",
  "battery",
  "control-center",
  "session"
]

[widget.workspaces]
change_color_on_hover = false
label_source = "name"
style = "minimal"

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"

[brightness]
enable_ddcutil = true

[control_center]
sidebar = "full"
sidebar_section = "none"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "keyboard_layout"

[[control_center.shortcuts]]
type = "bluetooth"
