[control_center]
sidebar = "full"
sidebar_section = "none"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "keyboard_layout"

[[control_center.shortcuts]]
type = "bluetooth"
